import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
# Check for direct TLS (bypass tailscale serve)
certfile = System.get_env("TLS_CERTFILE")
keyfile = System.get_env("TLS_KEYFILE")
port = String.to_integer(System.get_env("PORT") || "10000")

endpoint_config = [
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "/0fqm34XdSddQnofYiDoqbMr7tgBK9lSQ7VscnjBd0gHz9yO9OcqPH/Zute5kcUn",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:tether, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:tether, ~w(--watch)]}
  ]
]

endpoint_config =
  if certfile && keyfile do
    # Direct TLS - bind to all interfaces
    endpoint_config
    |> Keyword.put(:https,
      ip: {0, 0, 0, 0},
      port: port,
      cipher_suite: :strong,
      certfile: certfile,
      keyfile: keyfile
    )
    |> Keyword.put(:url,
      host: System.get_env("TAILSCALE_HOSTNAME", "localhost"),
      port: port,
      scheme: "https"
    )
  else
    # HTTP on localhost - tailscale serve proxies to here
    Keyword.put(endpoint_config, :http, ip: {127, 0, 0, 1}, port: port)
  end

config :tether, TetherWeb.Endpoint, endpoint_config

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :tether, TetherWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/tether_web/router\.ex$"E,
      ~r"lib/tether_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :tether, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
